# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nishan123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4b18514d474142c6931bd4e9539d907a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7f66c98a1229428e86dda46fe6a7a63c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4b18514d474142c6931bd4e9539d907a }}/mcr.microsoft.com/azuredocs/aci-helloworld:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nishan123'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3016413537c44f07be402ca7958c3518 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4b18514d474142c6931bd4e9539d907a }}/mcr.microsoft.com/azuredocs/aci-helloworld:${{ github.sha }}'